# Crate-level Cargo.toml template.
# This is copied into each generated PAC by `cargo xtask generate`.
# Only the top-level `Cargo.template.toml` should be modified.

[package]
name = "{{NAME}}-pac"
version = "0.9.0"
edition = "2018"
description = "Peripheral Access Crate for Nordic's {{NAME}} microcontroller"
keywords = ["no-std", "arm", "cortex-m", "nrf", "peripherals"]
license = "0BSD"
repository = "https://github.com/nrf-rs/nrf-pacs"
documentation = "https://docs.rs/{{NAME}}-pac"

[dependencies]
cortex-m = "0.7.3"
vcell = "0.1.3"

[dependencies.cortex-m-rt]
optional = true
version = "0.6.10"

[features]
rt = ["cortex-m-rt/device"]
